---
- name: Configurar Servidor de Banco de Dados
  hosts: db01

  user: vagrant
  become: yes
  var_files:
    - vars/main.yaml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devopsmaonamassa"
  tasks:
    - name: Configurar hosts do lab ansible
      lineinfile: line "{{item}}" path=/etc/hosts
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql

